name: Test

on: [push]

jobs:
  pytest:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Check cached datasets
      id: cache-datasets
      uses: actions/cache@v2
      with:
        path: ~/.cache/datasets
        key: datasets-${{ hashFiles('tests/.download_datasets.py') }}
          
    - name: Download datasetes if not cached
      if: steps.cache-datasets.outputs.cache-hit != 'true'
      run: |
        python ./tests/.download_datasets.py
        
    - name: pytest
      run: |
        pytest ./tests/